image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      flutter upgrade
      flutter config --android-sdk /home/gitpod/androidsdk
      yes | flutter doctor --android-licenses
      flutter doctor
      flutter pub get

ports:
  - port: 5900
    onOpen: ignore
# vnc
  - port: 6080
    onOpen: open-preview
# flutter
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code