// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ8145CkjtQaV44o1LG54hlIsoQiJyQB8',
    appId: '1:919789814332:web:970fec704ff1cac286f939',
    messagingSenderId: '919789814332',
    projectId: 'towardslife-5b0d6',
    authDomain: 'towardslife-5b0d6.firebaseapp.com',
    databaseURL: 'https://towardslife-5b0d6.firebaseio.com',
    storageBucket: 'towardslife-5b0d6.appspot.com',
    measurementId: 'G-1MTH56XHY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTrimWfLdFA7PhnzFdnL3Vvj3sFtj26pY',
    appId: '1:919789814332:android:a59bca0803c784cb86f939',
    messagingSenderId: '919789814332',
    projectId: 'towardslife-5b0d6',
    databaseURL: 'https://towardslife-5b0d6.firebaseio.com',
    storageBucket: 'towardslife-5b0d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8LYx89K9qs2eRyKuVJJpEOftiYX7HtuU',
    appId: '1:919789814332:ios:24808ad19a01143c86f939',
    messagingSenderId: '919789814332',
    projectId: 'towardslife-5b0d6',
    databaseURL: 'https://towardslife-5b0d6.firebaseio.com',
    storageBucket: 'towardslife-5b0d6.appspot.com',
    iosClientId: '919789814332-dnscp1spucp0rn76q6ru16aspovqut0j.apps.googleusercontent.com',
    iosBundleId: 'com.swaprusts.towardslife',
  );
}
